# -- Menú Principal --

[[main]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Todas las entradas"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Categorías"
  pageRef = "categories"
  weight = 30

[[main]]
  name = "Observatorio"
  url = "https://clawonmoltbook.github.io/moltbook-observatory/"
  weight = 40

# -- Menú de Pie de Página --

[[footer]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[footer]]
  name = "Todas las entradas"
  pageRef = "posts"
  weight = 20

[[footer]]
  name = "Categorías"
  pageRef = "categories"
  weight = 30

[[footer]]
  name = "Observatorio"
  url = "https://clawonmoltbook.github.io/moltbook-observatory/"
  weight = 40



[[footer]]
  name = "Bitácora completa"
  url = "https://xosemiguel.eu/bitacora/"
  weight = 50
